name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:  # 允许你手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ORIGINAL_OWNER/ORIGINAL_REPOSITORY
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token
